### ISSUE TITLE
[0.4.0] Workflow Task Scheduled event props incorrect

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/ui#338] opened 2022-03-16 03:22 UTC
<img width="1375" alt="Screen Shot 2022-03-15 at 11 22 17 PM" src="https://user-images.githubusercontent.com/119422/158510454-b2a7cd7a-b015-420a-b0ad-8ca513e78694.png">

Task queue property value is incorrect, it does not show the task queue name and kind. It seems its actually the workflow results displayed instead.

See v1 below for same event props:

<img width="1047" alt="Screen Shot 2022-03-15 at 11 22 08 PM" src="https://user-images.githubusercontent.com/119422/158510458-ddd0db66-2983-467a-bb3d-66f5947e3db5.png">

**Comment by stevekinney** [comment] 2022-03-16 13:59
Hmmm… I wonder if this is related to #304. I'll look at the payload and triage this one this morning.

**Comment by stevekinney** [comment] 2022-03-16 14:33
Oh, wait. I don't think we cut a release since #304. I _think_ this is fixed and a duplicate of #287. I can't recreate it in `main`, which leads me to believe it was fixed. So, I'm going to mark it as a duplicate for now and close this, but if it comes back up in the next release or when you're working off of `main`, definitely let us know.

**Closed by stevekinney** 2022-03-16 14:33 UTC
Labels: bug, ready

**Comment by tsurdilo** [comment] 2022-03-18 20:43
seems fixed in 0.5.0
